export const GET_MOVIES_BEGIN = 'GET_MOVIES_BEGIN';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';

export const GET_MOVIE_DETAIL_BEGIN = 'GET_MOVIE_DETAIL_BEGIN';
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
export const GET_MOVIE_DETAIL_FAIL = 'GET_MOVIE_DETAIL_FAIL';

export const GET_SIMILAR_MOVIES_BEGIN = 'GET_SIMILAR_MOVIES_BEGIN';
export const GET_SIMILAR_MOVIES_SUCCESS = 'GET_SIMILAR_MOVIES_SUCCESS';
export const GET_SIMILAR_MOVIES_FAIL = 'GET_SIMILAR_MOVIES_FAIL';

